//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArac()
        {
            this.tblKiralama = new HashSet<tblKiralama>();
        }
    
        public int aracId { get; set; }
        public Nullable<int> modelId { get; set; }
        public Nullable<bool> airbag { get; set; }
        public string aciklama { get; set; }
        public Nullable<decimal> gunlukFiyat { get; set; }
        public Nullable<int> koltukSayisi { get; set; }
        public Nullable<double> bagajHacmi { get; set; }
        public Nullable<int> km { get; set; }
        public string resim { get; set; }
    
        public virtual tblModel tblModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKiralama> tblKiralama { get; set; }
    }
}
