//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKiralama
    {
        public int kiralamaId { get; set; }
        public Nullable<bool> kiralamaDurum { get; set; }
        public Nullable<int> aracId { get; set; }
        public Nullable<int> musteriId { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> gunSayisi { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tblArac tblArac { get; set; }
        public virtual tblMusteri tblMusteri { get; set; }
    }
}
